import { Geist, Geist_Mono } from "next/font/google";
import "../globals.scss";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import Header2 from "@/components/layout/Header2";
import Footer2 from "@/components/layout/Footer2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ê Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <NextTopLoader />
      <Header2 />
      <main>
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
      </main>
      <Footer2/>
    </>
  );
}
