import "../globals.scss";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";

export const metadata = {
  title: "Ê Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <NextTopLoader />
      <main>
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
      </main>
    </>
  );
}
